# Generated by Django 4.0.4 on 2022-04-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_preco', models.FloatField()),
            ],
        ),
    ]
